- name: sample play
  hosts: localhost
  tasks:
    - debug:
        msg: Hello world
    - name: Install Nginx
      yum:
        name: nginx
        state: latest
    - name: Download azure artifacts
      shell: curl -s -L -o /tmp/frontend.zip "https://dev.azure.com/DevOps-Batches/ce99914a-0f7d-4c46-9ccc-e4d025115ea9/_apis/git/repositories/db389ddc-b576-4fd9-be14-b373d943d6ee/items?path=%2F&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&%24format=zip&api-version=5.0&download=true"
    - name: extract
      shell: unzip /tmp/frontend.zip
    - name: Update Nginx Configuration
      template:
          src: nginx.conf
          dest: /etc/nginx/nginx.conf

    - name: Start Nginx Service
      systemd:
        name: nginx
        state: started
        enabled: yes
      ignore_errors: yes