- name: sample play
  hosts: localhost
  tasks:
    - debug:
        msg: Hello world
    - name: Install Nginx
      yum:
        name: nginx
        state: latest
    - name: Update Nginx Configuration
      template:
          src: nginx.conf
          dest: /etc/nginx/nginx.conf
    - name: Start Nginx Service
      systemd:
        name: nginx
        state: started
        enabled: yes
      ignore_errors: yes
    - name: replace
      replace:
        path: /etc/nginx/nginx.conf
        regexp: 'dinesh1111'
        replace: 'dinesh'