- name: roboshop project setup with ansible
  hosts: localhost
  become: yes
  tasks:
    - name: Import frontend role
      import_role:
        name: frontend
        when: component == "frontend"
    - name: Import catalogue role
      import_role:
        name: catalogue
      when: component == "catalogue"
