- name: roboshop project setup with ansible
  hosts: localhost
  become: yes
  tasks:
    - name: Prechecks
      import_role:
        name: common
        tasks_from: prechecks
    - name: Import frontend role
      import_role:
        name: frontend
      when: component == "frontend"
      tags:
        - frontend

    - name: Import catalogue role
      import_role:
        name: catalogue
      when: component == "catalogue"
      tags:
        - catalogue