- name: how to declare variables
  hosts: localhost
  vars:
   URL: example.com
  tasks:
    - name: Print variable
      debug:
        msg: URL= {{URL}}
    - name: Print variable from task level
      vars:
        URL: google.com
      debug:
        msg: URL= {{URL}}
