- name: how to declare variables
  hosts: all
  vars:
   URL: example.com
  tasks:
    - name: Print variable
      debug:
        msg: URL= {{URL}}
    - name: Print variable from task level
      vars:
        URL: google.com
      debug:
        msg: URL= {{URL}}
- name: Declare variables in a file and access them
  hosts: all
  vars_files:
    - vars01.yml
  tasks:
    - name: Print variable from a file
      debug:
        msg: URL= {{URL}}
- name: Declare variable in command prompt
  hosts: all
  vars_prompt:
  - name: URL
    prompt: Enter URL
    private: no
  tasks:
    - name: Print variable from prompt
      debug:
      msg: URL= {{URL}}