- name: Install nginx
  yum:
    name: nginx
    state: present

- name: start nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Include AZ CLI Installation steps
  include_role:
     name: common
     tasks_from: az-cli-setup

- name: remove old htdocs
  file:
    path: usr/share/nginx/html
    state: absent

- name: create new htdocs
  file:
    path: usr/share/nginx/html
    state: directory

- name: Include artifact download steps
  include_role:
    name: common
    tasks_from: artifact-download