- name: Install NodeJS
  yum:
    name: ["nodejs", "make", "gcc-c++" ]
    state: present

- name: Add roboshop user
  user:
    name: roboshop

- name: Include AZ CLI Installation steps
  include_role:
    name: common
    tasks_from: az-cli-setup

- name: create artifact directory
  file:
    path: "{{ARTIFACT_PATH}}"
    state: directory

- name: Include artifact download steps
  include_role:
    name: common
    tasks_from: artifact-download

- name: Setup catalogue service
  template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Start catalogue service
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes

