- name: Include Steps for NodeJS
  include_role:
    name: common
    tasks_from: nodejs

- name: Include Steps for Rsyslog
  include_role:
    name: common
    tasks_from: rsyslog

- name: Setup Cart Service
  template:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: Start Cart Service
  systemd:
    name: cart
    state: restarted
    enabled: yes
    daemon_reload: yes
